name: signalforwarder

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build signaltracer
        run: go build -o signaltracer ./cmd/signaltracer

      - name: Build signalforwarder
        run: |
          mkdir signalforwarder
          go build -o signalforwarder/signalforwarder ./cmd/signalforwarder
          echo "PATH=$PWD/signalforwarder:$PATH" >> $GITHUB_ENV

      - name: Test signalforwarder
        run: |
          set -x
          set +e
          echo $PATH
          which signalforwarder
          signalforwarder -c true

      - name: Run signalforwarder + nested signaltracer (cancel this run to observe signals)
        shell: signalforwarder -e {0}
        run: |
          chmod +x signaldemo.sh
          exec ./signaltracer ./signaltracer bash signaldemo.sh
